### ISSUE TITLE
STATUS_PHRASES[status_code] KeyError: None

### ISSUE THREAD

**Issue by Aquinary** [MushroomMaula/fastapi_login#33]
I am trying to set a cookie for a user. When all checks are successful, return response returns the following error:

    ERROR:uvicorn.error:Exception in ASGI application
    Traceback (most recent call last):
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 396, in run_asgi
        result = await app(self.scope, self.receive, self.send)
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 45, in __call__
        return await self.app(scope, receive, send)
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\fastapi\applications.py", line 199, in __call__
        await super().__call__(scope, receive, send)
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\starlette\applications.py", line 111, in __call__
        await self.middleware_stack(scope, receive, send)
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
        raise exc from None
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
        await self.app(scope, receive, _send)
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\starlette\middleware\cors.py", line 86, in __call__
        await self.simple_response(scope, receive, send, request_headers=headers)
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\starlette\middleware\cors.py", line 142, in simple_response
        await self.app(scope, receive, send)
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\starlette\exceptions.py", line 82, in __call__
        raise exc from None
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\starlette\exceptions.py", line 71, in __call__
        await self.app(scope, receive, sender)
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\starlette\routing.py", line 566, in __call__
        await route.handle(scope, receive, send)
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\starlette\routing.py", line 227, in handle
        await self.app(scope, receive, send)
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\starlette\routing.py", line 44, in app
        await response(scope, receive, send)
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\starlette\responses.py", line 132, in __call__
        await send(
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\starlette\exceptions.py", line 68, in sender
        await send(message)
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\starlette\middleware\cors.py", line 167, in send
        await send(message)
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\starlette\middleware\errors.py", line 156, in _send
        await send(message)
      File "E:\Проекты\Веб\fastapi\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 471, in send
        reason = STATUS_PHRASES[status_code]
    KeyError: None

This is the authorization method itself. If I return a commented out return (c access_token), then everything is fine.
If I return a return response, I get the above error.

    @routers.post('/users/signin')
    async def user_signin(response: Response, data: OAuth2PasswordRequestForm = Depends()):
        """
        Создаём нового пользователя
        :param user: схематика
        :return:
        """
        errors = {}
    
        if not await validators.username_or_email_exists(data.username):
            errors['username'] = 'Пользователь не найден!'
    
        if not await services.password_check(data.username, data.password):
            errors['password'] = 'Данный пароль не подходит к учётной записи!'
    
        if not await services.email_activation_check(data.username):
            errors['is_email_activation'] = 'Вы не активировали аккаунт по ссылке в почте!'
    
        if (errors == {}):
            access_token = manager.create_access_token(
                data = dict(sub=data.username)
            )
            manager.set_cookie(response, access_token)
            #return {'access_token': access_token, 'token_type': 'bearer'}
            return response
        return errors

I don't understand what's going on, this part of the code is identical to your example.

**Comment by MushroomMaula** [comment]
Hey, judging from the stacktrace this does not to seem to be a error caused by fastapi_login.
Have you tried stepping through the stacktrace with a debugger to check whats actually causing the Exception? It seems like, when you return a response a status code is missing based on your Exception

**Comment by Aquinary** [comment]
> Hey, judging from the stacktrace this does not to seem to be a error caused by fastapi_login.
> Have you tried stepping through the stacktrace with a debugger to check whats actually causing the Exception? It seems like, when you return a response a status code is missing based on your Exception

The error disappeared when I made `response. status_code = 200`

**Comment by MushroomMaula** [comment]
When you want to return errors in a route it's propably a better idea to raise a [HTTPException](https://fastapi.tiangolo.com/tutorial/handling-errors/) as it allows setting a custom status code
